# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tf-terragrunt-statelock"
    dynamodb_table = "tf-terragrunt-statelock"
    encrypt        = true
    key            = "terragrunt/magento2/dev-aws-account/us-west-2/dev/aws-data/terraform.tfstate"
    profile        = "alignminds"
    region         = "us-west-2"
  }
}
